### ISSUE TITLE
Missing key refs

### ISSUE THREAD

**Issue by gfranxman** [peffjepin/tuindow#1]
There doesn't appear to be a key definition for TAB or ENTER like there are four all of the other special keys.

What's the right way to handle those, akin to the way tuindow.ESCAPE, tuindow.UP, tuiondow.DOWN, etc?

I just started playing with this library this morning, and I really like it.    I'm trying to implement a picker panel on top of existing panels.

**Comment by peffjepin** [comment]
Hello, you are correct that all the available keys were not implemented with constant values available to check against.

Curses has lots of key's available I've never encountered and I originally only implemented constants for the ones I use the most.

Enter and Tab can be checked against "\n" and "\t" respectively.

I just pushed out a new version.  This version has tuindow.ENTER and tuindow.TAB along with many other key constants.

```sh
pip install tuindow==1.0.2
```

Many of the newly implemented constants are for keys for which I am unfamiliar/aren't present on my keyboard for testing. The names for these keys are prefixed with KEY_ (ex: tuindow.KEY_CATAB) and their values give a hint as to what they are used for.

For a full accounting of what's now available you can use this command:

```sh
python3 -c "import tuindow; help(tuindow.SpecialKeys)"
```

**Comment by gfranxman** [comment]
Dewd, that was fast!   Thanks!
